addonPath: "PATH TO ~/World of Warcraft/_retail_/Interface/AddOns"

addons:
  bigwigs: False
  littlewigs: False
  details: False
  plater: False
  tomtom: False
  weakaura: False
  raiderio: False
  vuhdo: False
  bartender4: False
  true-stat-values: False
  narcissus: False
  elvui-windtools: False
  handynotes: False
  handynoteswarwithin: False
  mythic-dungeon-tools: False
  silverdragon: False

modIDs:
  bigwigs: 2382
  littlewigs: 4383
  details: 61284
  plater: 100547
  tomtom: 18808
  weakaura: 65387
  raiderio: 279257
  vuhdo: 7950
  bartender4: 13501
  true-stat-values: 437378
  narcissus: 311718
  elvui-windtools: 300361
  handynotes: 14154
  handynoteswarwithin: 932955
  mythic-dungeon-tools: 288981
  silverdragon: 14647

api: "https://www.curseforge.com/api/v1/mods/"